# Site settings
title: ITMaximum
email: mail@itmaximum.ru
description: > # this means to ignore newlines until "baseurl:"
  Разработка сайтов, продвижение, техническая поддержка, доступные цены
  и особый подход к каждому клиенту.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://itmaximum.ru" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
